apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluecollar-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Blue-Kollar/Blue-Collar
    targetRevision: main
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: bluecollar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
